/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPublicAdminCopilotRouteImport } from './routes/api/public/admin-copilot'
import { Route as ApiPublicAdminDeleteUserRouteImport } from './routes/api/public/admin-delete-user'
import { Route as ApiPublicAiStatusRouteImport } from './routes/api/public/ai-status'
import { Route as ApiPublicAiTestRouteImport } from './routes/api/public/ai-test'
import { Route as ApiPublicAthenaRouteImport } from './routes/api/public/athena'
import { Route as ApiPublicKbAutocourseRouteImport } from './routes/api/public/kb-autocourse'
import { Route as ApiPublicKbClassifyRouteImport } from './routes/api/public/kb-classify'
import { Route as ApiPublicKbDriveRouteImport } from './routes/api/public/kb-drive'
import { Route as ApiPublicKbEditalRouteImport } from './routes/api/public/kb-edital'
import { Route as ApiPublicKbIngestRouteImport } from './routes/api/public/kb-ingest'
import { Route as ApiPublicLacunasRouteImport } from './routes/api/public/lacunas'
import { Route as ApiPublicPodcastRouteImport } from './routes/api/public/podcast'
import { Route as ApiPublicRedacaoRouteImport } from './routes/api/public/redacao'
import { Route as ApiPublicResumoRouteImport } from './routes/api/public/resumo'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as ApiPublicHotmartWebhookRouteImport } from './routes/api/public/hotmart/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminCopilotRoute = ApiPublicAdminCopilotRouteImport.update({
  id: '/api/public/admin-copilot',
  path: '/api/public/admin-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDeleteUserRoute =
  ApiPublicAdminDeleteUserRouteImport.update({
    id: '/api/public/admin-delete-user',
    path: '/api/public/admin-delete-user',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiStatusRoute = ApiPublicAiStatusRouteImport.update({
  id: '/api/public/ai-status',
  path: '/api/public/ai-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiTestRoute = ApiPublicAiTestRouteImport.update({
  id: '/api/public/ai-test',
  path: '/api/public/ai-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAthenaRoute = ApiPublicAthenaRouteImport.update({
  id: '/api/public/athena',
  path: '/api/public/athena',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbAutocourseRoute = ApiPublicKbAutocourseRouteImport.update({
  id: '/api/public/kb-autocourse',
  path: '/api/public/kb-autocourse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbClassifyRoute = ApiPublicKbClassifyRouteImport.update({
  id: '/api/public/kb-classify',
  path: '/api/public/kb-classify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbDriveRoute = ApiPublicKbDriveRouteImport.update({
  id: '/api/public/kb-drive',
  path: '/api/public/kb-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbEditalRoute = ApiPublicKbEditalRouteImport.update({
  id: '/api/public/kb-edital',
  path: '/api/public/kb-edital',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbIngestRoute = ApiPublicKbIngestRouteImport.update({
  id: '/api/public/kb-ingest',
  path: '/api/public/kb-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLacunasRoute = ApiPublicLacunasRouteImport.update({
  id: '/api/public/lacunas',
  path: '/api/public/lacunas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPodcastRoute = ApiPublicPodcastRouteImport.update({
  id: '/api/public/podcast',
  path: '/api/public/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRedacaoRoute = ApiPublicRedacaoRouteImport.update({
  id: '/api/public/redacao',
  path: '/api/public/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResumoRoute = ApiPublicResumoRouteImport.update({
  id: '/api/public/resumo',
  path: '/api/public/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHotmartWebhookRoute = ApiPublicHotmartWebhookRouteImport.update({
  id: '/api/public/hotmart/webhook',
  path: '/api/public/hotmart/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/admin-copilot': typeof ApiPublicAdminCopilotRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/ai-status': typeof ApiPublicAiStatusRoute
  '/api/public/ai-test': typeof ApiPublicAiTestRoute
  '/api/public/athena': typeof ApiPublicAthenaRoute
  '/api/public/kb-autocourse': typeof ApiPublicKbAutocourseRoute
  '/api/public/kb-classify': typeof ApiPublicKbClassifyRoute
  '/api/public/kb-drive': typeof ApiPublicKbDriveRoute
  '/api/public/kb-edital': typeof ApiPublicKbEditalRoute
  '/api/public/kb-ingest': typeof ApiPublicKbIngestRoute
  '/api/public/lacunas': typeof ApiPublicLacunasRoute
  '/api/public/podcast': typeof ApiPublicPodcastRoute
  '/api/public/redacao': typeof ApiPublicRedacaoRoute
  '/api/public/resumo': typeof ApiPublicResumoRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/admin-copilot': typeof ApiPublicAdminCopilotRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/ai-status': typeof ApiPublicAiStatusRoute
  '/api/public/ai-test': typeof ApiPublicAiTestRoute
  '/api/public/athena': typeof ApiPublicAthenaRoute
  '/api/public/kb-autocourse': typeof ApiPublicKbAutocourseRoute
  '/api/public/kb-classify': typeof ApiPublicKbClassifyRoute
  '/api/public/kb-drive': typeof ApiPublicKbDriveRoute
  '/api/public/kb-edital': typeof ApiPublicKbEditalRoute
  '/api/public/kb-ingest': typeof ApiPublicKbIngestRoute
  '/api/public/lacunas': typeof ApiPublicLacunasRoute
  '/api/public/podcast': typeof ApiPublicPodcastRoute
  '/api/public/redacao': typeof ApiPublicRedacaoRoute
  '/api/public/resumo': typeof ApiPublicResumoRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/admin-copilot': typeof ApiPublicAdminCopilotRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/ai-status': typeof ApiPublicAiStatusRoute
  '/api/public/ai-test': typeof ApiPublicAiTestRoute
  '/api/public/athena': typeof ApiPublicAthenaRoute
  '/api/public/kb-autocourse': typeof ApiPublicKbAutocourseRoute
  '/api/public/kb-classify': typeof ApiPublicKbClassifyRoute
  '/api/public/kb-drive': typeof ApiPublicKbDriveRoute
  '/api/public/kb-edital': typeof ApiPublicKbEditalRoute
  '/api/public/kb-ingest': typeof ApiPublicKbIngestRoute
  '/api/public/lacunas': typeof ApiPublicLacunasRoute
  '/api/public/podcast': typeof ApiPublicPodcastRoute
  '/api/public/redacao': typeof ApiPublicRedacaoRoute
  '/api/public/resumo': typeof ApiPublicResumoRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/admin-copilot'
    | '/api/public/admin-delete-user'
    | '/api/public/ai-status'
    | '/api/public/ai-test'
    | '/api/public/athena'
    | '/api/public/kb-autocourse'
    | '/api/public/kb-classify'
    | '/api/public/kb-drive'
    | '/api/public/kb-edital'
    | '/api/public/kb-ingest'
    | '/api/public/lacunas'
    | '/api/public/podcast'
    | '/api/public/redacao'
    | '/api/public/resumo'
    | '/api/public/tts'
    | '/api/public/hotmart/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/admin-copilot'
    | '/api/public/admin-delete-user'
    | '/api/public/ai-status'
    | '/api/public/ai-test'
    | '/api/public/athena'
    | '/api/public/kb-autocourse'
    | '/api/public/kb-classify'
    | '/api/public/kb-drive'
    | '/api/public/kb-edital'
    | '/api/public/kb-ingest'
    | '/api/public/lacunas'
    | '/api/public/podcast'
    | '/api/public/redacao'
    | '/api/public/resumo'
    | '/api/public/tts'
    | '/api/public/hotmart/webhook'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/admin-copilot'
    | '/api/public/admin-delete-user'
    | '/api/public/ai-status'
    | '/api/public/ai-test'
    | '/api/public/athena'
    | '/api/public/kb-autocourse'
    | '/api/public/kb-classify'
    | '/api/public/kb-drive'
    | '/api/public/kb-edital'
    | '/api/public/kb-ingest'
    | '/api/public/lacunas'
    | '/api/public/podcast'
    | '/api/public/redacao'
    | '/api/public/resumo'
    | '/api/public/tts'
    | '/api/public/hotmart/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAdminCopilotRoute: typeof ApiPublicAdminCopilotRoute
  ApiPublicAdminDeleteUserRoute: typeof ApiPublicAdminDeleteUserRoute
  ApiPublicAiStatusRoute: typeof ApiPublicAiStatusRoute
  ApiPublicAiTestRoute: typeof ApiPublicAiTestRoute
  ApiPublicAthenaRoute: typeof ApiPublicAthenaRoute
  ApiPublicKbAutocourseRoute: typeof ApiPublicKbAutocourseRoute
  ApiPublicKbClassifyRoute: typeof ApiPublicKbClassifyRoute
  ApiPublicKbDriveRoute: typeof ApiPublicKbDriveRoute
  ApiPublicKbEditalRoute: typeof ApiPublicKbEditalRoute
  ApiPublicKbIngestRoute: typeof ApiPublicKbIngestRoute
  ApiPublicLacunasRoute: typeof ApiPublicLacunasRoute
  ApiPublicPodcastRoute: typeof ApiPublicPodcastRoute
  ApiPublicRedacaoRoute: typeof ApiPublicRedacaoRoute
  ApiPublicResumoRoute: typeof ApiPublicResumoRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  ApiPublicHotmartWebhookRoute: typeof ApiPublicHotmartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-copilot': {
      id: '/api/public/admin-copilot'
      path: '/api/public/admin-copilot'
      fullPath: '/api/public/admin-copilot'
      preLoaderRoute: typeof ApiPublicAdminCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-delete-user': {
      id: '/api/public/admin-delete-user'
      path: '/api/public/admin-delete-user'
      fullPath: '/api/public/admin-delete-user'
      preLoaderRoute: typeof ApiPublicAdminDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-status': {
      id: '/api/public/ai-status'
      path: '/api/public/ai-status'
      fullPath: '/api/public/ai-status'
      preLoaderRoute: typeof ApiPublicAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-test': {
      id: '/api/public/ai-test'
      path: '/api/public/ai-test'
      fullPath: '/api/public/ai-test'
      preLoaderRoute: typeof ApiPublicAiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/athena': {
      id: '/api/public/athena'
      path: '/api/public/athena'
      fullPath: '/api/public/athena'
      preLoaderRoute: typeof ApiPublicAthenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-autocourse': {
      id: '/api/public/kb-autocourse'
      path: '/api/public/kb-autocourse'
      fullPath: '/api/public/kb-autocourse'
      preLoaderRoute: typeof ApiPublicKbAutocourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-classify': {
      id: '/api/public/kb-classify'
      path: '/api/public/kb-classify'
      fullPath: '/api/public/kb-classify'
      preLoaderRoute: typeof ApiPublicKbClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-drive': {
      id: '/api/public/kb-drive'
      path: '/api/public/kb-drive'
      fullPath: '/api/public/kb-drive'
      preLoaderRoute: typeof ApiPublicKbDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-edital': {
      id: '/api/public/kb-edital'
      path: '/api/public/kb-edital'
      fullPath: '/api/public/kb-edital'
      preLoaderRoute: typeof ApiPublicKbEditalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-ingest': {
      id: '/api/public/kb-ingest'
      path: '/api/public/kb-ingest'
      fullPath: '/api/public/kb-ingest'
      preLoaderRoute: typeof ApiPublicKbIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lacunas': {
      id: '/api/public/lacunas'
      path: '/api/public/lacunas'
      fullPath: '/api/public/lacunas'
      preLoaderRoute: typeof ApiPublicLacunasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/podcast': {
      id: '/api/public/podcast'
      path: '/api/public/podcast'
      fullPath: '/api/public/podcast'
      preLoaderRoute: typeof ApiPublicPodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/redacao': {
      id: '/api/public/redacao'
      path: '/api/public/redacao'
      fullPath: '/api/public/redacao'
      preLoaderRoute: typeof ApiPublicRedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resumo': {
      id: '/api/public/resumo'
      path: '/api/public/resumo'
      fullPath: '/api/public/resumo'
      preLoaderRoute: typeof ApiPublicResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hotmart/webhook': {
      id: '/api/public/hotmart/webhook'
      path: '/api/public/hotmart/webhook'
      fullPath: '/api/public/hotmart/webhook'
      preLoaderRoute: typeof ApiPublicHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAdminCopilotRoute: ApiPublicAdminCopilotRoute,
  ApiPublicAdminDeleteUserRoute: ApiPublicAdminDeleteUserRoute,
  ApiPublicAiStatusRoute: ApiPublicAiStatusRoute,
  ApiPublicAiTestRoute: ApiPublicAiTestRoute,
  ApiPublicAthenaRoute: ApiPublicAthenaRoute,
  ApiPublicKbAutocourseRoute: ApiPublicKbAutocourseRoute,
  ApiPublicKbClassifyRoute: ApiPublicKbClassifyRoute,
  ApiPublicKbDriveRoute: ApiPublicKbDriveRoute,
  ApiPublicKbEditalRoute: ApiPublicKbEditalRoute,
  ApiPublicKbIngestRoute: ApiPublicKbIngestRoute,
  ApiPublicLacunasRoute: ApiPublicLacunasRoute,
  ApiPublicPodcastRoute: ApiPublicPodcastRoute,
  ApiPublicRedacaoRoute: ApiPublicRedacaoRoute,
  ApiPublicResumoRoute: ApiPublicResumoRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  ApiPublicHotmartWebhookRoute: ApiPublicHotmartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
