/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPublicAdminCopilotRouteImport } from './routes/api/public/admin-copilot'
import { Route as ApiPublicAdminDeleteUserRouteImport } from './routes/api/public/admin-delete-user'
import { Route as ApiPublicAiCentralRouteImport } from './routes/api/public/ai-central'
import { Route as ApiPublicAiKeysRouteImport } from './routes/api/public/ai-keys'
import { Route as ApiPublicAiStatusRouteImport } from './routes/api/public/ai-status'
import { Route as ApiPublicAiTestRouteImport } from './routes/api/public/ai-test'
import { Route as ApiPublicAthenaRouteImport } from './routes/api/public/athena'
import { Route as ApiPublicAulaHtmlRouteImport } from './routes/api/public/aula-html'
import { Route as ApiPublicAulaIaRouteImport } from './routes/api/public/aula-ia'
import { Route as ApiPublicAulaPacoteRouteImport } from './routes/api/public/aula-pacote'
import { Route as ApiPublicAulaStatusRouteImport } from './routes/api/public/aula-status'
import { Route as ApiPublicGerarExerciciosRouteImport } from './routes/api/public/gerar-exercicios'
import { Route as ApiPublicKbAuditoriaRouteImport } from './routes/api/public/kb-auditoria'
import { Route as ApiPublicKbAulaRouteImport } from './routes/api/public/kb-aula'
import { Route as ApiPublicKbAutocourseRouteImport } from './routes/api/public/kb-autocourse'
import { Route as ApiPublicKbClassifyRouteImport } from './routes/api/public/kb-classify'
import { Route as ApiPublicKbDriveRouteImport } from './routes/api/public/kb-drive'
import { Route as ApiPublicKbEditalRouteImport } from './routes/api/public/kb-edital'
import { Route as ApiPublicKbEmbedRouteImport } from './routes/api/public/kb-embed'
import { Route as ApiPublicKbIngestRouteImport } from './routes/api/public/kb-ingest'
import { Route as ApiPublicKbPrepararRouteImport } from './routes/api/public/kb-preparar'
import { Route as ApiPublicKbQuestoesReaisRouteImport } from './routes/api/public/kb-questoes-reais'
import { Route as ApiPublicLacunasRouteImport } from './routes/api/public/lacunas'
import { Route as ApiPublicMapaRouteImport } from './routes/api/public/mapa'
import { Route as ApiPublicPodcastRouteImport } from './routes/api/public/podcast'
import { Route as ApiPublicRagMetricsRouteImport } from './routes/api/public/rag-metrics'
import { Route as ApiPublicRagPreviewRouteImport } from './routes/api/public/rag-preview'
import { Route as ApiPublicRagSettingsRouteImport } from './routes/api/public/rag-settings'
import { Route as ApiPublicRedacaoRouteImport } from './routes/api/public/redacao'
import { Route as ApiPublicResumoRouteImport } from './routes/api/public/resumo'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as ApiPublicHotmartWebhookRouteImport } from './routes/api/public/hotmart/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminCopilotRoute = ApiPublicAdminCopilotRouteImport.update({
  id: '/api/public/admin-copilot',
  path: '/api/public/admin-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDeleteUserRoute =
  ApiPublicAdminDeleteUserRouteImport.update({
    id: '/api/public/admin-delete-user',
    path: '/api/public/admin-delete-user',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiCentralRoute = ApiPublicAiCentralRouteImport.update({
  id: '/api/public/ai-central',
  path: '/api/public/ai-central',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiKeysRoute = ApiPublicAiKeysRouteImport.update({
  id: '/api/public/ai-keys',
  path: '/api/public/ai-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiStatusRoute = ApiPublicAiStatusRouteImport.update({
  id: '/api/public/ai-status',
  path: '/api/public/ai-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiTestRoute = ApiPublicAiTestRouteImport.update({
  id: '/api/public/ai-test',
  path: '/api/public/ai-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAthenaRoute = ApiPublicAthenaRouteImport.update({
  id: '/api/public/athena',
  path: '/api/public/athena',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAulaHtmlRoute = ApiPublicAulaHtmlRouteImport.update({
  id: '/api/public/aula-html',
  path: '/api/public/aula-html',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAulaIaRoute = ApiPublicAulaIaRouteImport.update({
  id: '/api/public/aula-ia',
  path: '/api/public/aula-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAulaPacoteRoute = ApiPublicAulaPacoteRouteImport.update({
  id: '/api/public/aula-pacote',
  path: '/api/public/aula-pacote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAulaStatusRoute = ApiPublicAulaStatusRouteImport.update({
  id: '/api/public/aula-status',
  path: '/api/public/aula-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGerarExerciciosRoute =
  ApiPublicGerarExerciciosRouteImport.update({
    id: '/api/public/gerar-exercicios',
    path: '/api/public/gerar-exercicios',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKbAuditoriaRoute = ApiPublicKbAuditoriaRouteImport.update({
  id: '/api/public/kb-auditoria',
  path: '/api/public/kb-auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbAulaRoute = ApiPublicKbAulaRouteImport.update({
  id: '/api/public/kb-aula',
  path: '/api/public/kb-aula',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbAutocourseRoute = ApiPublicKbAutocourseRouteImport.update({
  id: '/api/public/kb-autocourse',
  path: '/api/public/kb-autocourse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbClassifyRoute = ApiPublicKbClassifyRouteImport.update({
  id: '/api/public/kb-classify',
  path: '/api/public/kb-classify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbDriveRoute = ApiPublicKbDriveRouteImport.update({
  id: '/api/public/kb-drive',
  path: '/api/public/kb-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbEditalRoute = ApiPublicKbEditalRouteImport.update({
  id: '/api/public/kb-edital',
  path: '/api/public/kb-edital',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbEmbedRoute = ApiPublicKbEmbedRouteImport.update({
  id: '/api/public/kb-embed',
  path: '/api/public/kb-embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbIngestRoute = ApiPublicKbIngestRouteImport.update({
  id: '/api/public/kb-ingest',
  path: '/api/public/kb-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbPrepararRoute = ApiPublicKbPrepararRouteImport.update({
  id: '/api/public/kb-preparar',
  path: '/api/public/kb-preparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKbQuestoesReaisRoute =
  ApiPublicKbQuestoesReaisRouteImport.update({
    id: '/api/public/kb-questoes-reais',
    path: '/api/public/kb-questoes-reais',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLacunasRoute = ApiPublicLacunasRouteImport.update({
  id: '/api/public/lacunas',
  path: '/api/public/lacunas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMapaRoute = ApiPublicMapaRouteImport.update({
  id: '/api/public/mapa',
  path: '/api/public/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPodcastRoute = ApiPublicPodcastRouteImport.update({
  id: '/api/public/podcast',
  path: '/api/public/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRagMetricsRoute = ApiPublicRagMetricsRouteImport.update({
  id: '/api/public/rag-metrics',
  path: '/api/public/rag-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRagPreviewRoute = ApiPublicRagPreviewRouteImport.update({
  id: '/api/public/rag-preview',
  path: '/api/public/rag-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRagSettingsRoute = ApiPublicRagSettingsRouteImport.update({
  id: '/api/public/rag-settings',
  path: '/api/public/rag-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRedacaoRoute = ApiPublicRedacaoRouteImport.update({
  id: '/api/public/redacao',
  path: '/api/public/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResumoRoute = ApiPublicResumoRouteImport.update({
  id: '/api/public/resumo',
  path: '/api/public/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHotmartWebhookRoute = ApiPublicHotmartWebhookRouteImport.update({
  id: '/api/public/hotmart/webhook',
  path: '/api/public/hotmart/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/admin-copilot': typeof ApiPublicAdminCopilotRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/ai-central': typeof ApiPublicAiCentralRoute
  '/api/public/ai-keys': typeof ApiPublicAiKeysRoute
  '/api/public/ai-status': typeof ApiPublicAiStatusRoute
  '/api/public/ai-test': typeof ApiPublicAiTestRoute
  '/api/public/athena': typeof ApiPublicAthenaRoute
  '/api/public/aula-html': typeof ApiPublicAulaHtmlRoute
  '/api/public/aula-ia': typeof ApiPublicAulaIaRoute
  '/api/public/aula-pacote': typeof ApiPublicAulaPacoteRoute
  '/api/public/aula-status': typeof ApiPublicAulaStatusRoute
  '/api/public/gerar-exercicios': typeof ApiPublicGerarExerciciosRoute
  '/api/public/kb-auditoria': typeof ApiPublicKbAuditoriaRoute
  '/api/public/kb-aula': typeof ApiPublicKbAulaRoute
  '/api/public/kb-autocourse': typeof ApiPublicKbAutocourseRoute
  '/api/public/kb-classify': typeof ApiPublicKbClassifyRoute
  '/api/public/kb-drive': typeof ApiPublicKbDriveRoute
  '/api/public/kb-edital': typeof ApiPublicKbEditalRoute
  '/api/public/kb-embed': typeof ApiPublicKbEmbedRoute
  '/api/public/kb-ingest': typeof ApiPublicKbIngestRoute
  '/api/public/kb-preparar': typeof ApiPublicKbPrepararRoute
  '/api/public/kb-questoes-reais': typeof ApiPublicKbQuestoesReaisRoute
  '/api/public/lacunas': typeof ApiPublicLacunasRoute
  '/api/public/mapa': typeof ApiPublicMapaRoute
  '/api/public/podcast': typeof ApiPublicPodcastRoute
  '/api/public/rag-metrics': typeof ApiPublicRagMetricsRoute
  '/api/public/rag-preview': typeof ApiPublicRagPreviewRoute
  '/api/public/rag-settings': typeof ApiPublicRagSettingsRoute
  '/api/public/redacao': typeof ApiPublicRedacaoRoute
  '/api/public/resumo': typeof ApiPublicResumoRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/admin-copilot': typeof ApiPublicAdminCopilotRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/ai-central': typeof ApiPublicAiCentralRoute
  '/api/public/ai-keys': typeof ApiPublicAiKeysRoute
  '/api/public/ai-status': typeof ApiPublicAiStatusRoute
  '/api/public/ai-test': typeof ApiPublicAiTestRoute
  '/api/public/athena': typeof ApiPublicAthenaRoute
  '/api/public/aula-html': typeof ApiPublicAulaHtmlRoute
  '/api/public/aula-ia': typeof ApiPublicAulaIaRoute
  '/api/public/aula-pacote': typeof ApiPublicAulaPacoteRoute
  '/api/public/aula-status': typeof ApiPublicAulaStatusRoute
  '/api/public/gerar-exercicios': typeof ApiPublicGerarExerciciosRoute
  '/api/public/kb-auditoria': typeof ApiPublicKbAuditoriaRoute
  '/api/public/kb-aula': typeof ApiPublicKbAulaRoute
  '/api/public/kb-autocourse': typeof ApiPublicKbAutocourseRoute
  '/api/public/kb-classify': typeof ApiPublicKbClassifyRoute
  '/api/public/kb-drive': typeof ApiPublicKbDriveRoute
  '/api/public/kb-edital': typeof ApiPublicKbEditalRoute
  '/api/public/kb-embed': typeof ApiPublicKbEmbedRoute
  '/api/public/kb-ingest': typeof ApiPublicKbIngestRoute
  '/api/public/kb-preparar': typeof ApiPublicKbPrepararRoute
  '/api/public/kb-questoes-reais': typeof ApiPublicKbQuestoesReaisRoute
  '/api/public/lacunas': typeof ApiPublicLacunasRoute
  '/api/public/mapa': typeof ApiPublicMapaRoute
  '/api/public/podcast': typeof ApiPublicPodcastRoute
  '/api/public/rag-metrics': typeof ApiPublicRagMetricsRoute
  '/api/public/rag-preview': typeof ApiPublicRagPreviewRoute
  '/api/public/rag-settings': typeof ApiPublicRagSettingsRoute
  '/api/public/redacao': typeof ApiPublicRedacaoRoute
  '/api/public/resumo': typeof ApiPublicResumoRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/admin-copilot': typeof ApiPublicAdminCopilotRoute
  '/api/public/admin-delete-user': typeof ApiPublicAdminDeleteUserRoute
  '/api/public/ai-central': typeof ApiPublicAiCentralRoute
  '/api/public/ai-keys': typeof ApiPublicAiKeysRoute
  '/api/public/ai-status': typeof ApiPublicAiStatusRoute
  '/api/public/ai-test': typeof ApiPublicAiTestRoute
  '/api/public/athena': typeof ApiPublicAthenaRoute
  '/api/public/aula-html': typeof ApiPublicAulaHtmlRoute
  '/api/public/aula-ia': typeof ApiPublicAulaIaRoute
  '/api/public/aula-pacote': typeof ApiPublicAulaPacoteRoute
  '/api/public/aula-status': typeof ApiPublicAulaStatusRoute
  '/api/public/gerar-exercicios': typeof ApiPublicGerarExerciciosRoute
  '/api/public/kb-auditoria': typeof ApiPublicKbAuditoriaRoute
  '/api/public/kb-aula': typeof ApiPublicKbAulaRoute
  '/api/public/kb-autocourse': typeof ApiPublicKbAutocourseRoute
  '/api/public/kb-classify': typeof ApiPublicKbClassifyRoute
  '/api/public/kb-drive': typeof ApiPublicKbDriveRoute
  '/api/public/kb-edital': typeof ApiPublicKbEditalRoute
  '/api/public/kb-embed': typeof ApiPublicKbEmbedRoute
  '/api/public/kb-ingest': typeof ApiPublicKbIngestRoute
  '/api/public/kb-preparar': typeof ApiPublicKbPrepararRoute
  '/api/public/kb-questoes-reais': typeof ApiPublicKbQuestoesReaisRoute
  '/api/public/lacunas': typeof ApiPublicLacunasRoute
  '/api/public/mapa': typeof ApiPublicMapaRoute
  '/api/public/podcast': typeof ApiPublicPodcastRoute
  '/api/public/rag-metrics': typeof ApiPublicRagMetricsRoute
  '/api/public/rag-preview': typeof ApiPublicRagPreviewRoute
  '/api/public/rag-settings': typeof ApiPublicRagSettingsRoute
  '/api/public/redacao': typeof ApiPublicRedacaoRoute
  '/api/public/resumo': typeof ApiPublicResumoRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/hotmart/webhook': typeof ApiPublicHotmartWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/admin-copilot'
    | '/api/public/admin-delete-user'
    | '/api/public/ai-central'
    | '/api/public/ai-keys'
    | '/api/public/ai-status'
    | '/api/public/ai-test'
    | '/api/public/athena'
    | '/api/public/aula-html'
    | '/api/public/aula-ia'
    | '/api/public/aula-pacote'
    | '/api/public/aula-status'
    | '/api/public/gerar-exercicios'
    | '/api/public/kb-auditoria'
    | '/api/public/kb-aula'
    | '/api/public/kb-autocourse'
    | '/api/public/kb-classify'
    | '/api/public/kb-drive'
    | '/api/public/kb-edital'
    | '/api/public/kb-embed'
    | '/api/public/kb-ingest'
    | '/api/public/kb-preparar'
    | '/api/public/kb-questoes-reais'
    | '/api/public/lacunas'
    | '/api/public/mapa'
    | '/api/public/podcast'
    | '/api/public/rag-metrics'
    | '/api/public/rag-preview'
    | '/api/public/rag-settings'
    | '/api/public/redacao'
    | '/api/public/resumo'
    | '/api/public/tts'
    | '/api/public/hotmart/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/admin-copilot'
    | '/api/public/admin-delete-user'
    | '/api/public/ai-central'
    | '/api/public/ai-keys'
    | '/api/public/ai-status'
    | '/api/public/ai-test'
    | '/api/public/athena'
    | '/api/public/aula-html'
    | '/api/public/aula-ia'
    | '/api/public/aula-pacote'
    | '/api/public/aula-status'
    | '/api/public/gerar-exercicios'
    | '/api/public/kb-auditoria'
    | '/api/public/kb-aula'
    | '/api/public/kb-autocourse'
    | '/api/public/kb-classify'
    | '/api/public/kb-drive'
    | '/api/public/kb-edital'
    | '/api/public/kb-embed'
    | '/api/public/kb-ingest'
    | '/api/public/kb-preparar'
    | '/api/public/kb-questoes-reais'
    | '/api/public/lacunas'
    | '/api/public/mapa'
    | '/api/public/podcast'
    | '/api/public/rag-metrics'
    | '/api/public/rag-preview'
    | '/api/public/rag-settings'
    | '/api/public/redacao'
    | '/api/public/resumo'
    | '/api/public/tts'
    | '/api/public/hotmart/webhook'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/admin-copilot'
    | '/api/public/admin-delete-user'
    | '/api/public/ai-central'
    | '/api/public/ai-keys'
    | '/api/public/ai-status'
    | '/api/public/ai-test'
    | '/api/public/athena'
    | '/api/public/aula-html'
    | '/api/public/aula-ia'
    | '/api/public/aula-pacote'
    | '/api/public/aula-status'
    | '/api/public/gerar-exercicios'
    | '/api/public/kb-auditoria'
    | '/api/public/kb-aula'
    | '/api/public/kb-autocourse'
    | '/api/public/kb-classify'
    | '/api/public/kb-drive'
    | '/api/public/kb-edital'
    | '/api/public/kb-embed'
    | '/api/public/kb-ingest'
    | '/api/public/kb-preparar'
    | '/api/public/kb-questoes-reais'
    | '/api/public/lacunas'
    | '/api/public/mapa'
    | '/api/public/podcast'
    | '/api/public/rag-metrics'
    | '/api/public/rag-preview'
    | '/api/public/rag-settings'
    | '/api/public/redacao'
    | '/api/public/resumo'
    | '/api/public/tts'
    | '/api/public/hotmart/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAdminCopilotRoute: typeof ApiPublicAdminCopilotRoute
  ApiPublicAdminDeleteUserRoute: typeof ApiPublicAdminDeleteUserRoute
  ApiPublicAiCentralRoute: typeof ApiPublicAiCentralRoute
  ApiPublicAiKeysRoute: typeof ApiPublicAiKeysRoute
  ApiPublicAiStatusRoute: typeof ApiPublicAiStatusRoute
  ApiPublicAiTestRoute: typeof ApiPublicAiTestRoute
  ApiPublicAthenaRoute: typeof ApiPublicAthenaRoute
  ApiPublicAulaHtmlRoute: typeof ApiPublicAulaHtmlRoute
  ApiPublicAulaIaRoute: typeof ApiPublicAulaIaRoute
  ApiPublicAulaPacoteRoute: typeof ApiPublicAulaPacoteRoute
  ApiPublicAulaStatusRoute: typeof ApiPublicAulaStatusRoute
  ApiPublicGerarExerciciosRoute: typeof ApiPublicGerarExerciciosRoute
  ApiPublicKbAuditoriaRoute: typeof ApiPublicKbAuditoriaRoute
  ApiPublicKbAulaRoute: typeof ApiPublicKbAulaRoute
  ApiPublicKbAutocourseRoute: typeof ApiPublicKbAutocourseRoute
  ApiPublicKbClassifyRoute: typeof ApiPublicKbClassifyRoute
  ApiPublicKbDriveRoute: typeof ApiPublicKbDriveRoute
  ApiPublicKbEditalRoute: typeof ApiPublicKbEditalRoute
  ApiPublicKbEmbedRoute: typeof ApiPublicKbEmbedRoute
  ApiPublicKbIngestRoute: typeof ApiPublicKbIngestRoute
  ApiPublicKbPrepararRoute: typeof ApiPublicKbPrepararRoute
  ApiPublicKbQuestoesReaisRoute: typeof ApiPublicKbQuestoesReaisRoute
  ApiPublicLacunasRoute: typeof ApiPublicLacunasRoute
  ApiPublicMapaRoute: typeof ApiPublicMapaRoute
  ApiPublicPodcastRoute: typeof ApiPublicPodcastRoute
  ApiPublicRagMetricsRoute: typeof ApiPublicRagMetricsRoute
  ApiPublicRagPreviewRoute: typeof ApiPublicRagPreviewRoute
  ApiPublicRagSettingsRoute: typeof ApiPublicRagSettingsRoute
  ApiPublicRedacaoRoute: typeof ApiPublicRedacaoRoute
  ApiPublicResumoRoute: typeof ApiPublicResumoRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  ApiPublicHotmartWebhookRoute: typeof ApiPublicHotmartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-copilot': {
      id: '/api/public/admin-copilot'
      path: '/api/public/admin-copilot'
      fullPath: '/api/public/admin-copilot'
      preLoaderRoute: typeof ApiPublicAdminCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-delete-user': {
      id: '/api/public/admin-delete-user'
      path: '/api/public/admin-delete-user'
      fullPath: '/api/public/admin-delete-user'
      preLoaderRoute: typeof ApiPublicAdminDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-central': {
      id: '/api/public/ai-central'
      path: '/api/public/ai-central'
      fullPath: '/api/public/ai-central'
      preLoaderRoute: typeof ApiPublicAiCentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-keys': {
      id: '/api/public/ai-keys'
      path: '/api/public/ai-keys'
      fullPath: '/api/public/ai-keys'
      preLoaderRoute: typeof ApiPublicAiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-status': {
      id: '/api/public/ai-status'
      path: '/api/public/ai-status'
      fullPath: '/api/public/ai-status'
      preLoaderRoute: typeof ApiPublicAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-test': {
      id: '/api/public/ai-test'
      path: '/api/public/ai-test'
      fullPath: '/api/public/ai-test'
      preLoaderRoute: typeof ApiPublicAiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/athena': {
      id: '/api/public/athena'
      path: '/api/public/athena'
      fullPath: '/api/public/athena'
      preLoaderRoute: typeof ApiPublicAthenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aula-html': {
      id: '/api/public/aula-html'
      path: '/api/public/aula-html'
      fullPath: '/api/public/aula-html'
      preLoaderRoute: typeof ApiPublicAulaHtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aula-ia': {
      id: '/api/public/aula-ia'
      path: '/api/public/aula-ia'
      fullPath: '/api/public/aula-ia'
      preLoaderRoute: typeof ApiPublicAulaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aula-pacote': {
      id: '/api/public/aula-pacote'
      path: '/api/public/aula-pacote'
      fullPath: '/api/public/aula-pacote'
      preLoaderRoute: typeof ApiPublicAulaPacoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aula-status': {
      id: '/api/public/aula-status'
      path: '/api/public/aula-status'
      fullPath: '/api/public/aula-status'
      preLoaderRoute: typeof ApiPublicAulaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gerar-exercicios': {
      id: '/api/public/gerar-exercicios'
      path: '/api/public/gerar-exercicios'
      fullPath: '/api/public/gerar-exercicios'
      preLoaderRoute: typeof ApiPublicGerarExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-auditoria': {
      id: '/api/public/kb-auditoria'
      path: '/api/public/kb-auditoria'
      fullPath: '/api/public/kb-auditoria'
      preLoaderRoute: typeof ApiPublicKbAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-aula': {
      id: '/api/public/kb-aula'
      path: '/api/public/kb-aula'
      fullPath: '/api/public/kb-aula'
      preLoaderRoute: typeof ApiPublicKbAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-autocourse': {
      id: '/api/public/kb-autocourse'
      path: '/api/public/kb-autocourse'
      fullPath: '/api/public/kb-autocourse'
      preLoaderRoute: typeof ApiPublicKbAutocourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-classify': {
      id: '/api/public/kb-classify'
      path: '/api/public/kb-classify'
      fullPath: '/api/public/kb-classify'
      preLoaderRoute: typeof ApiPublicKbClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-drive': {
      id: '/api/public/kb-drive'
      path: '/api/public/kb-drive'
      fullPath: '/api/public/kb-drive'
      preLoaderRoute: typeof ApiPublicKbDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-edital': {
      id: '/api/public/kb-edital'
      path: '/api/public/kb-edital'
      fullPath: '/api/public/kb-edital'
      preLoaderRoute: typeof ApiPublicKbEditalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-embed': {
      id: '/api/public/kb-embed'
      path: '/api/public/kb-embed'
      fullPath: '/api/public/kb-embed'
      preLoaderRoute: typeof ApiPublicKbEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-ingest': {
      id: '/api/public/kb-ingest'
      path: '/api/public/kb-ingest'
      fullPath: '/api/public/kb-ingest'
      preLoaderRoute: typeof ApiPublicKbIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-preparar': {
      id: '/api/public/kb-preparar'
      path: '/api/public/kb-preparar'
      fullPath: '/api/public/kb-preparar'
      preLoaderRoute: typeof ApiPublicKbPrepararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kb-questoes-reais': {
      id: '/api/public/kb-questoes-reais'
      path: '/api/public/kb-questoes-reais'
      fullPath: '/api/public/kb-questoes-reais'
      preLoaderRoute: typeof ApiPublicKbQuestoesReaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lacunas': {
      id: '/api/public/lacunas'
      path: '/api/public/lacunas'
      fullPath: '/api/public/lacunas'
      preLoaderRoute: typeof ApiPublicLacunasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mapa': {
      id: '/api/public/mapa'
      path: '/api/public/mapa'
      fullPath: '/api/public/mapa'
      preLoaderRoute: typeof ApiPublicMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/podcast': {
      id: '/api/public/podcast'
      path: '/api/public/podcast'
      fullPath: '/api/public/podcast'
      preLoaderRoute: typeof ApiPublicPodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rag-metrics': {
      id: '/api/public/rag-metrics'
      path: '/api/public/rag-metrics'
      fullPath: '/api/public/rag-metrics'
      preLoaderRoute: typeof ApiPublicRagMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rag-preview': {
      id: '/api/public/rag-preview'
      path: '/api/public/rag-preview'
      fullPath: '/api/public/rag-preview'
      preLoaderRoute: typeof ApiPublicRagPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rag-settings': {
      id: '/api/public/rag-settings'
      path: '/api/public/rag-settings'
      fullPath: '/api/public/rag-settings'
      preLoaderRoute: typeof ApiPublicRagSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/redacao': {
      id: '/api/public/redacao'
      path: '/api/public/redacao'
      fullPath: '/api/public/redacao'
      preLoaderRoute: typeof ApiPublicRedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resumo': {
      id: '/api/public/resumo'
      path: '/api/public/resumo'
      fullPath: '/api/public/resumo'
      preLoaderRoute: typeof ApiPublicResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hotmart/webhook': {
      id: '/api/public/hotmart/webhook'
      path: '/api/public/hotmart/webhook'
      fullPath: '/api/public/hotmart/webhook'
      preLoaderRoute: typeof ApiPublicHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAdminCopilotRoute: ApiPublicAdminCopilotRoute,
  ApiPublicAdminDeleteUserRoute: ApiPublicAdminDeleteUserRoute,
  ApiPublicAiCentralRoute: ApiPublicAiCentralRoute,
  ApiPublicAiKeysRoute: ApiPublicAiKeysRoute,
  ApiPublicAiStatusRoute: ApiPublicAiStatusRoute,
  ApiPublicAiTestRoute: ApiPublicAiTestRoute,
  ApiPublicAthenaRoute: ApiPublicAthenaRoute,
  ApiPublicAulaHtmlRoute: ApiPublicAulaHtmlRoute,
  ApiPublicAulaIaRoute: ApiPublicAulaIaRoute,
  ApiPublicAulaPacoteRoute: ApiPublicAulaPacoteRoute,
  ApiPublicAulaStatusRoute: ApiPublicAulaStatusRoute,
  ApiPublicGerarExerciciosRoute: ApiPublicGerarExerciciosRoute,
  ApiPublicKbAuditoriaRoute: ApiPublicKbAuditoriaRoute,
  ApiPublicKbAulaRoute: ApiPublicKbAulaRoute,
  ApiPublicKbAutocourseRoute: ApiPublicKbAutocourseRoute,
  ApiPublicKbClassifyRoute: ApiPublicKbClassifyRoute,
  ApiPublicKbDriveRoute: ApiPublicKbDriveRoute,
  ApiPublicKbEditalRoute: ApiPublicKbEditalRoute,
  ApiPublicKbEmbedRoute: ApiPublicKbEmbedRoute,
  ApiPublicKbIngestRoute: ApiPublicKbIngestRoute,
  ApiPublicKbPrepararRoute: ApiPublicKbPrepararRoute,
  ApiPublicKbQuestoesReaisRoute: ApiPublicKbQuestoesReaisRoute,
  ApiPublicLacunasRoute: ApiPublicLacunasRoute,
  ApiPublicMapaRoute: ApiPublicMapaRoute,
  ApiPublicPodcastRoute: ApiPublicPodcastRoute,
  ApiPublicRagMetricsRoute: ApiPublicRagMetricsRoute,
  ApiPublicRagPreviewRoute: ApiPublicRagPreviewRoute,
  ApiPublicRagSettingsRoute: ApiPublicRagSettingsRoute,
  ApiPublicRedacaoRoute: ApiPublicRedacaoRoute,
  ApiPublicResumoRoute: ApiPublicResumoRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  ApiPublicHotmartWebhookRoute: ApiPublicHotmartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
