-- Substitui a lista de topicos (91, divergente) pela taxonomia completa e precisa de public/data.js (302 topicos).
-- Seguro: nenhuma outra tabela tem FK para topics.id (progresso/questoes/flashcards usam topic_nome em texto),
-- e o produto ainda nao foi lancado (sem progresso real de aluno a preservar).
DELETE FROM public.topics;

-- Língua Portuguesa (21 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Compreensão e Interpretação de Textos', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Tipologia e Gêneros Textuais', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Coesão e Coerência Textual', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Funções da Linguagem', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Ortografia Oficial', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Acentuação Gráfica', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Emprego do Sinal Indicativo de Crase', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Classes de Palavras', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Emprego dos Tempos e Modos Verbais', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Sintaxe da Oração e do Período', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Termos da Oração', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Orações Coordenadas e Subordinadas', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Concordância Verbal', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Concordância Nominal', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Regência Verbal', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Regência Nominal', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Colocação Pronominal', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Pontuação', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Significação das Palavras (Semântica)', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Reescrita e Equivalência de Frases', 20),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Portuguesa'), 'Redação Oficial (Manual da Presidência da República)', 21);

-- Raciocínio Lógico-Matemático (20 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Estruturas Lógicas', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Lógica Sentencial (Proposicional)', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Tabelas-Verdade', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Equivalências e Negações (De Morgan)', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Lógica de Argumentação: Inferências e Deduções', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Diagramas Lógicos', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Lógica de Primeira Ordem', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Operações com Conjuntos', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Problemas Aritméticos e Matriciais', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Sequências e Séries', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Razão e Proporção', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Regra de Três Simples e Composta', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Porcentagem', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Juros Simples e Compostos', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Princípios de Contagem', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Análise Combinatória', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Probabilidade', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Estatística Descritiva', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Medidas de Tendência Central e Dispersão', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Raciocínio Lógico-Matemático'), 'Análise de Gráficos e Tabelas', 20);

-- Informática (20 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Conceitos de Internet e Intranet', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Navegadores (Chrome, Firefox, Edge)', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Correio Eletrônico', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Busca e Pesquisa na Internet', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Redes Sociais e Grupos de Discussão', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Computação em Nuvem', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Organização e Gerenciamento de Arquivos e Pastas', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Sistema Operacional Windows 10', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Sistema Operacional Linux', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Microsoft Word', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Microsoft Excel', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Microsoft PowerPoint', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'LibreOffice (Writer, Calc, Impress)', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Segurança da Informação: Conceitos e Procedimentos', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Vírus, Worms e Pragas Virtuais', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Antivírus, Firewall e Antispyware', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Criptografia e Certificação Digital', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Procedimentos de Backup', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Redes de Computadores', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Informática'), 'Noções de Banco de Dados', 20);

-- Física (19 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Grandezas, Unidades e Vetores', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Cinemática: MRU e MRUV', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Lançamentos e Movimento Circular', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Leis de Newton', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Força de Atrito', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Trabalho e Potência', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Energia e Conservação da Energia Mecânica', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Quantidade de Movimento e Colisões', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Estática e Equilíbrio de Corpos', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Gravitação Universal', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Hidrostática', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Termologia e Calorimetria', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Termodinâmica', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Óptica Geométrica', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Ondulatória e Acústica', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Eletrostática', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Eletrodinâmica e Circuitos Elétricos', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Eletromagnetismo', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Física'), 'Física Aplicada ao Trânsito: Frenagem e Colisões', 19);

-- Ética no Serviço Público (14 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Ética e Moral: Conceitos Fundamentais', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Ética, Princípios e Valores', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Ética e Democracia: Exercício da Cidadania', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Ética e Função Pública', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Ética no Setor Público', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Código de Ética do Servidor (Decreto 1.171/1994)', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Comissões de Ética', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Lei 8.112/1990: Deveres e Proibições', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Regime Disciplinar e Responsabilidades do Servidor', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Improbidade Administrativa (Lei 8.429/1992)', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Conflito de Interesses (Lei 12.813/2013)', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Código de Conduta da Alta Administração Federal', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Lei de Acesso à Informação (12.527/2011)', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Ética no Serviço Público'), 'Processo Administrativo (Lei 9.784/1999)', 14);

-- Geopolítica Brasileira (19 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Formação Territorial do Brasil', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Organização Político-Administrativa', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Regionalização do Brasil (IBGE e Geoeconômica)', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Fronteiras e Faixa de Fronteira', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Países Limítrofes e Integração Sul-Americana', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Domínios Morfoclimáticos', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Recursos Naturais e Meio Ambiente', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Amazônia e Questões Ambientais', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Dinâmica Demográfica e Migrações', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Urbanização e Rede Urbana', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Estrutura Fundiária e Questão Agrária', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Economia Brasileira e Setores Produtivos', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Matriz Energética', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Transportes e Logística Nacional', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Rodovias Federais e Malha Viária', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Comércio Exterior e Mercosul', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Brasil no Cenário Geopolítico Mundial', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Segurança Pública, Fronteiras e Crime Transnacional', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Geopolítica Brasileira'), 'Ecoturismo e Patrimônio Ambiental', 19);

-- Língua Inglesa (15 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Reading Comprehension', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Vocabulary and Cognates', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Word Formation', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Verb Tenses', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Modal Verbs', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Passive Voice', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Conditional Sentences', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Relative Clauses', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Reported Speech', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Pronouns', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Adjectives and Adverbs', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Prepositions', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Conjunctions and Connectors', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Phrasal Verbs', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Inglesa'), 'Textual Interpretation of Technical Texts', 15);

-- Língua Espanhola (14 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Comprensión de Textos Escritos', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Vocabulario y Falsos Cognados', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Artículos y Sustantivos', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Adjetivos', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Pronombres', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Tiempos Verbales del Indicativo', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Modo Subjuntivo', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Perífrasis Verbales', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Preposiciones', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Conectores y Marcadores Discursivos', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Voz Pasiva', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Oraciones Condicionales', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Acentuación y Ortografía', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Língua Espanhola'), 'Heterogenéricos, Heterotónicos y Heterosemánticos', 14);

-- Legislação de Trânsito (23 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Disposições Preliminares do CTB', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Sistema Nacional de Trânsito: Composição e Competências', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Normas Gerais de Circulação e Conduta', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Educação para o Trânsito', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Sinalização de Trânsito', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Engenharia de Tráfego, Operação e Fiscalização', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Policiamento Ostensivo de Trânsito', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Veículos: Classificação e Segurança', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Registro e Licenciamento de Veículos', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Condução de Escolares e Transporte de Passageiros', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Habilitação: CNH e Permissão para Dirigir', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Infrações de Trânsito', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Penalidades', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Medidas Administrativas', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Processo Administrativo: Autuação, Defesa e Recursos (JARI/CETRAN)', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Crimes de Trânsito', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Resoluções do CONTRAN', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Transporte de Cargas: Pesos e Dimensões', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Transporte de Produtos Perigosos', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Equipamentos Obrigatórios e Dispositivos de Retenção', 20),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Anexo I do CTB: Conceitos e Definições', 21),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Direção Defensiva', 22),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação de Trânsito'), 'Primeiros Socorros no Trânsito', 23);

-- Direito Administrativo (27 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Estado, Governo e Administração Pública', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Conceito, Fontes e Princípios do Direito Administrativo', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Regime Jurídico-Administrativo', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Organização Administrativa: Direta e Indireta', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Autarquias, Fundações, Empresas Públicas e Sociedades de Economia Mista', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Entidades Paraestatais e Terceiro Setor', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Poderes Administrativos', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Poder de Polícia', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Ato Administrativo: Conceito, Requisitos e Atributos', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Classificação e Espécies de Atos Administrativos', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Extinção e Invalidação dos Atos Administrativos', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Processo Administrativo (Lei 9.784/1999)', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Agentes Públicos: Classificação e Regime', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Lei 8.112/1990: Provimento e Vacância', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Direitos, Vantagens e Deveres do Servidor', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Processo Administrativo Disciplinar', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Licitações: Lei 14.133/2021', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Licitações: Lei 8.666/1993 e Pregão (Lei 10.520/2002)', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Contratos Administrativos', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Serviços Públicos: Concessão e Permissão (Lei 8.987/1995)', 20),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Controle da Administração Pública', 21),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Controle Externo e Tribunal de Contas', 22),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Responsabilidade Civil do Estado', 23),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Improbidade Administrativa (Lei 8.429/1992)', 24),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Bens Públicos', 25),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Intervenção do Estado na Propriedade', 26),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Administrativo'), 'Lei de Acesso à Informação (12.527/2011)', 27);

-- Direito Constitucional (26 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Constituição: Conceito, Classificação e Aplicabilidade das Normas', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Poder Constituinte', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Princípios Fundamentais', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Direitos e Deveres Individuais e Coletivos', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Remédios Constitucionais', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Direitos Sociais', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Nacionalidade', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Direitos Políticos', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Partidos Políticos', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Organização Político-Administrativa do Estado', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Repartição de Competências', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'União, Estados, Distrito Federal e Municípios', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Intervenção Federal', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Administração Pública na Constituição (arts. 37 a 41)', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Servidores Públicos na Constituição', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Poder Legislativo: Organização e Atribuições', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Processo Legislativo', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Fiscalização Contábil, Financeira e Orçamentária', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Poder Executivo: Atribuições e Responsabilidades', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Poder Judiciário: Organização e Competências', 20),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Funções Essenciais à Justiça', 21),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Defesa do Estado e das Instituições Democráticas', 22),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Segurança Pública (art. 144) e a Polícia Rodoviária Federal', 23),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Controle de Constitucionalidade', 24),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Ordem Econômica e Financeira', 25),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Constitucional'), 'Ordem Social', 26);

-- Direito Penal (25 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Aplicação da Lei Penal e Princípios', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Lei Penal no Tempo', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Lei Penal no Espaço', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Teoria do Crime: Fato Típico', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Nexo Causal e Imputação Objetiva', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Ilicitude e Excludentes', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Culpabilidade e Excludentes', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Imputabilidade Penal', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Crime Consumado e Tentado', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Desistência Voluntária e Arrependimento', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Erro de Tipo e Erro de Proibição', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Concurso de Pessoas', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Concurso de Crimes', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Penas: Espécies e Cominação', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Aplicação da Pena e Dosimetria', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Efeitos da Condenação e Medidas de Segurança', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Suspensão Condicional da Pena e Livramento Condicional', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Extinção da Punibilidade e Prescrição', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Crimes contra a Pessoa', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Crimes contra o Patrimônio', 20),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Crimes contra a Dignidade Sexual', 21),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Crimes contra a Fé Pública', 22),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Crimes contra a Incolumidade Pública', 23),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Crimes contra a Administração Pública', 24),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Penal'), 'Crimes Praticados por Funcionário Público', 25);

-- Direito Processual Penal (23 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Princípios e Aplicação da Lei Processual Penal', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Inquérito Policial', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Polícia Judiciária e Polícia Administrativa', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Ação Penal Pública e Privada', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Jurisdição e Competência', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Prova: Princípios e Meios de Prova', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Ônus da Prova e Cadeia de Custódia', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Busca e Apreensão', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Interceptação Telefônica (Lei 9.296/1996)', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Prisão em Flagrante', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Prisão Preventiva e Temporária', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Medidas Cautelares Diversas da Prisão', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Liberdade Provisória e Fiança', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Audiência de Custódia', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Citações e Intimações', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Sentença Penal', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Procedimentos Comuns e Especiais', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Tribunal do Júri', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Nulidades', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Recursos em Espécie', 20),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Habeas Corpus e Mandado de Segurança Criminal', 21),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Juizados Especiais Criminais (Lei 9.099/1995)', 22),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direito Processual Penal'), 'Acordo de Não Persecução Penal', 23);

-- Legislação Penal Especial (17 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Lei de Drogas (11.343/2006)', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Estatuto do Desarmamento (10.826/2003)', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Crimes Hediondos (8.072/1990)', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Lei de Tortura (9.455/1997)', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Lei Maria da Penha (11.340/2006)', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Abuso de Autoridade (13.869/2019)', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Organização Criminosa (12.850/2013)', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Lavagem de Dinheiro (9.613/1998)', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Crimes Ambientais (9.605/1998)', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Estatuto da Criança e do Adolescente: Aspectos Penais', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Estatuto do Idoso: Aspectos Penais', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Contravenções Penais (DL 3.688/1941)', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Crimes de Trânsito (Lei 9.503/1997)', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Identificação Criminal (Lei 12.037/2009)', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Terrorismo (Lei 13.260/2016)', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Tráfico de Pessoas (Lei 13.344/2016)', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Legislação Penal Especial'), 'Crimes de Trânsito e Legislação Extravagante Correlata', 17);

-- Direitos Humanos e Cidadania (20 topicos)
INSERT INTO public.topics (discipline_id, nome, ordem) VALUES
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Teoria Geral dos Direitos Humanos', 1),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Afirmação Histórica e Dimensões dos Direitos Humanos', 2),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Declaração Universal dos Direitos Humanos (1948)', 3),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Sistema Global de Proteção (ONU)', 4),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Pactos Internacionais de 1966', 5),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Sistema Interamericano e Pacto de San José', 6),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Corte Interamericana de Direitos Humanos', 7),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Direitos Humanos na Constituição de 1988', 8),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Incorporação de Tratados Internacionais', 9),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Programa Nacional de Direitos Humanos (PNDH-3)', 10),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Código de Conduta para Encarregados da Aplicação da Lei', 11),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Princípios Básicos sobre o Uso da Força e Armas de Fogo', 12),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Regras de Mandela e Tratamento de Presos', 13),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Direitos Humanos e Atividade Policial', 14),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Convenção contra a Tortura', 15),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Convenção sobre a Eliminação da Discriminação Racial', 16),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Convenção sobre os Direitos da Criança', 17),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Convenção sobre os Direitos das Pessoas com Deficiência', 18),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Estatuto da Igualdade Racial (Lei 12.288/2010)', 19),
  ((SELECT id FROM public.disciplines WHERE nome = 'Direitos Humanos e Cidadania'), 'Cidadania e Participação Social', 20);
